package BuildingExecutive;

import Resident.ResidentUpdate_CM;
import cClasses.BuildingExecutive;
import cClasses.Complaint;
import cClasses.Functions;
import cClasses.Jobs;
import cClasses.Patrolling;
import cClasses.Patrols;
import cClasses.Security;
import cClasses.Session;
import com.mycompany.group9_oopj.Main_Page;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class Building_Executive_Main extends javax.swing.JFrame {
    Session Session;
    String id;
    ArrayList<BuildingExecutive> buildingexecutives = new BuildingExecutive().Import();
    ArrayList<Security> securities = new Security().Import();
    ArrayList<Complaint> complaints = new Complaint().Import();
    ArrayList<Patrols> patrols = new Patrols().Import();
    
    Complaint.fileManipulation c = new Complaint.fileManipulation();
    Jobs.getInfo j = new Jobs.getInfo();
    Patrolling.getInfo p = new Patrolling.getInfo();
    
    /**
     * Creates new form Building_Executive_Main
     * @param session
     */
    public Building_Executive_Main(Session session) {
        initComponents();
        this.Session = session;
        id = Session.getId(); 
        Security.tabulateData(securities, JobManagementTbl);
        Patrols.tabulateData(patrols, PatrollingTbl);
        Complaint.tabulateData2(complaints, ComplaintsTbl);
        Patrols.tabulateData(patrols, PatrollingHistoryTbl);
        
        securities = new Security().Import();
        complaints = new Complaint().Import();
        patrols = new Patrols().Import();
        ArrayList<String> securitydata;
        securitydata = Functions.Read("Security.txt");
        String emid = "";
        for(BuildingExecutive b:buildingexecutives){
            String username = b.getName();
            String userID = b.getId();
            String buildingexecutiveId= b.getId();
            if(id.equals(buildingexecutiveId)){
                
                Username.setText(username);
                UID.setText(userID);
            
            }
        }
        
        dt(); //Input Date and Time
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    // For Date and Time
    Timer t;
    SimpleDateFormat st;
    
    public void dt(){
    
        // Date
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String dd = sdf.format(d);
        Date.setText(dd);
        
        // Time
        t = new Timer (0, new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                
                String tt = st.format(dt);
                Time.setText(tt);
            }
        }); 
           t.start(); 
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UID = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Logout1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emName = new javax.swing.JTextField();
        emEmail = new javax.swing.JTextField();
        emID = new javax.swing.JTextField();
        emRole = new javax.swing.JTextField();
        emContact = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        JobManagementTbl = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jClearBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jAssignBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emPassword = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ComplaintsTbl = new javax.swing.JTable();
        cUpdateBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PatrollingHistoryTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pAssignBtn = new javax.swing.JButton();
        pDeleteBtn = new javax.swing.JButton();
        pClearBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PatrollingTbl = new javax.swing.JTable();
        psTime = new javax.swing.JTextField();
        psDate = new javax.swing.JTextField();
        psCID = new javax.swing.JTextField();
        psSID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        psStatus = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(114, 126, 224));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Building Executive");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Parkhill Residence");

        Username.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        UID.setForeground(new java.awt.Color(255, 255, 255));
        UID.setText("UID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(173, 173, 173)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(UID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Username))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UID)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(67, 63, 113));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Logout1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Logout1.setForeground(new java.awt.Color(255, 255, 255));
        Logout1.setText("    Logout");
        Logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jLabel1.setText("Name:");

        jLabel4.setText("ID:");

        jLabel5.setText("Role:");

        jLabel6.setText("Email:");

        jLabel7.setText("Contact No:");

        emRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emRoleActionPerformed(evt);
            }
        });

        JobManagementTbl.setBackground(new java.awt.Color(204, 204, 204));
        JobManagementTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Role", "Email", "Password", "Contact No."
            }
        ));
        JobManagementTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JobManagementTblMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(JobManagementTbl);

        jLabel9.setText("Employees");

        jClearBtn.setText("Clear");
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        jUpdateBtn.setText("Update");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });

        jDeleteBtn.setText("Delete");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });

        jAssignBtn.setText("Assign");
        jAssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAssignBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Password:");

        emPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emContact, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(emPassword)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emID)
                                    .addComponent(emRole)
                                    .addComponent(emEmail)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(259, 259, 259)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jClearBtn)
                            .addComponent(jAssignBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUpdateBtn)
                            .addComponent(jDeleteBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(emRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(emEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(emPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(emContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClearBtn)
                            .addComponent(jUpdateBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAssignBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Job Management", jPanel2);

        jLabel15.setText("Complaints");

        ComplaintsTbl.setBackground(new java.awt.Color(204, 204, 204));
        ComplaintsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complaint ID", "User ID", "Description", "Date", "Status"
            }
        ));
        ComplaintsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComplaintsTblMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(ComplaintsTbl);

        cUpdateBtn.setText("Update");
        cUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cUpdateBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(292, 292, 292))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cUpdateBtn)
                        .addGap(31, 31, 31))))
        );

        jTabbedPane1.addTab("Complaints", jPanel4);

        jLabel17.setText("History");

        PatrollingHistoryTbl.setBackground(new java.awt.Color(204, 204, 204));
        PatrollingHistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Checkpoint ID", "Security ID", "Date", "Time"
            }
        ));
        PatrollingHistoryTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PatrollingHistoryTblMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(PatrollingHistoryTbl);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(340, 340, 340))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patrolling History", jPanel6);

        jLabel10.setText("Secuirty ID:");

        jLabel11.setText("Checkpoint ID:");

        jLabel12.setText("Time:");

        jLabel13.setText("Date:");

        pAssignBtn.setText("Assign");
        pAssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAssignBtnActionPerformed(evt);
            }
        });

        pDeleteBtn.setText("Delete");
        pDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDeleteBtnActionPerformed(evt);
            }
        });

        pClearBtn.setText("Clear");
        pClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pClearBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Patrolling Schedules");

        PatrollingTbl.setBackground(new java.awt.Color(204, 204, 204));
        PatrollingTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Checkpoint ID", "Security ID", "Date", "Time", "Status"
            }
        ));
        PatrollingTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PatrollingTblMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(PatrollingTbl);

        psTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psTimeActionPerformed(evt);
            }
        });

        psDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psDateActionPerformed(evt);
            }
        });

        psSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psSIDActionPerformed(evt);
            }
        });

        jLabel18.setText("Status:");

        psStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(191, 191, 191))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pAssignBtn)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(psCID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel18))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(psSID, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                                            .addComponent(psDate, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                                            .addComponent(psStatus)))))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(psTime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(pClearBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pDeleteBtn)
                                .addGap(40, 40, 40)))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(psCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(psSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(psTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(psStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAssignBtn)
                    .addComponent(pDeleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pClearBtn)
                .addGap(16, 16, 16))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patrolling Schedule", jPanel3);

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date.setText("Date");

        Time.setBackground(new java.awt.Color(0, 0, 0));
        Time.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("Time");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time)
                    .addComponent(Date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseClicked
        Main_Page MP = new Main_Page();
        MP.show(); //display Main Page

        dispose(); //close current frame after open new frame
    }//GEN-LAST:event_Logout1MouseClicked

    private void JobManagementTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobManagementTblMousePressed
        if(JobManagementTbl.getSelectedRow() != -1){
            emName.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 0).toString());
            emID.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 1).toString());
            emRole.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 2).toString());
            emEmail.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 3).toString());
            emPassword.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 4).toString());
            emContact.setText(JobManagementTbl.getValueAt(JobManagementTbl.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_JobManagementTblMousePressed

    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        JobManagementTbl.clearSelection();
        emName.setText("");
        emID.setText("");
        emRole.setText("");
        emEmail.setText("");
        emPassword.setText("");
        emContact.setText("");
    }//GEN-LAST:event_jClearBtnActionPerformed

    private void jAssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAssignBtnActionPerformed
        String x = emID.getText().replaceAll("[0-9]", "");
        if(x.equals("BM") || x.equals("AE") || x.equals("AD") || x.equals("BEXEC") || x.equals("RE") || x.equals("VE")){
            JOptionPane.showMessageDialog(null, "You Don't Have Access!");
        }else{
            if (!emID.getText().equals("") || 
                !emName.getText().equals("") || 
                !emEmail.getText().equals("") || 
                !emPassword.getText().equals("") || 
                !emRole.getText().equals("") || 
                !emContact.getText().equals("")) 
            {
                j.addFile(emID.getText(), 
                        emName.getText(), 
                        emEmail.getText(),
                        emPassword.getText(),
                        emRole.getText(),
                        emContact.getText());
                securities.add(new Security(emID.getText(), 
                        emName.getText(), 
                        emEmail.getText(),
                        emPassword.getText(),
                        emRole.getText(),
                        emContact.getText()));
                JOptionPane.showMessageDialog(null, "Successfully Assigned Job!");
                
            } else {
                JOptionPane.showMessageDialog(null, "Missing Inputs");
            }
            DefaultTableModel model = (DefaultTableModel)JobManagementTbl.getModel();
            model.setRowCount(0);
            Security.tabulateData(securities, JobManagementTbl);
        } 
    
    }//GEN-LAST:event_jAssignBtnActionPerformed

    private void pClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pClearBtnActionPerformed
        PatrollingTbl.clearSelection();
        psCID.setText("");
        psSID.setText("");
        psTime.setText("");
        psDate.setText("");
        psStatus.setText("");
    }//GEN-LAST:event_pClearBtnActionPerformed

    private void PatrollingTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatrollingTblMousePressed
        if(PatrollingTbl.getSelectedRow() != -1){
            psCID.setText(PatrollingTbl.getValueAt(PatrollingTbl.getSelectedRow(), 0).toString());
            psSID.setText(PatrollingTbl.getValueAt(PatrollingTbl.getSelectedRow(), 1).toString());
            psTime.setText(PatrollingTbl.getValueAt(PatrollingTbl.getSelectedRow(), 2).toString());
            psDate.setText(PatrollingTbl.getValueAt(PatrollingTbl.getSelectedRow(), 3).toString());
            psStatus.setText(PatrollingTbl.getValueAt(PatrollingTbl.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_PatrollingTblMousePressed

    private void ComplaintsTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComplaintsTblMousePressed
       
    }//GEN-LAST:event_ComplaintsTblMousePressed

    private void PatrollingHistoryTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatrollingHistoryTblMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatrollingHistoryTblMousePressed

    private void emRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emRoleActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        String Id = emID.getText();
        String name = emName.getText();
        String email = emEmail.getText();
        String password = emPassword.getText();
        String role = emRole.getText();
        String contact = emContact.getText();
        
        ArrayList<String> emdata;
        emdata=Functions.Read("Security.txt");
        for(String i:emdata){
                String[] j = i.split(":");
                    if(j[1].equals(Id)){
                        Id=j[1];
                    }
                }
        securities = new Security(Id, name, email, password, role, contact).Update(securities, Id);
        JOptionPane.showMessageDialog(null, "Successfully Updated");
        
        try (BufferedReader brrr = new BufferedReader(new FileReader("Security.txt"))) {
            String line;
            Scanner reader = new Scanner(brrr);
            while ((line = brrr.readLine()) != null) {
                String[] list = line.split(":");
                String SecurityId = list[0];
                String SecurityName = list [1];
                String SecurityEmail = list[2];
                String SecurityPassword = list[3];
                String SecurityContact = list [5];
                
            if (emID.equals(SecurityId)) {    
                emName.setText(SecurityName);
                emEmail.setText(SecurityEmail);
                emPassword.setText(SecurityPassword);
                emContact.setText(SecurityContact);
                } }
            }   
    catch (Exception e) {  
            }
    JOptionPane.showMessageDialog(null,"Your Details Have Been Modified and Refreshed");    

    DefaultTableModel model = (DefaultTableModel)JobManagementTbl.getModel();
    model.setRowCount(0);
    Security.tabulateData(securities, JobManagementTbl);
    
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if (JobManagementTbl.getSelectionModel().isSelectionEmpty() == false) {
        int column = 1;
        int rowIndex = JobManagementTbl.getSelectedRow();
        String Id = JobManagementTbl.getModel().getValueAt(JobManagementTbl.convertRowIndexToModel(rowIndex), column).toString();

        securities = Security.delete(securities, Id, rowIndex);

        DefaultTableModel model = (DefaultTableModel) JobManagementTbl.getModel();
        model.setRowCount(0);
        for (Security s : securities) {
            model.addRow(new Object[]{s.getId(), s.getName(), s.getContactNo()});
        }

        Building_Executive_Main bem = new Building_Executive_Main(Session);
        bem.setVisible(true);
        dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void emPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emPasswordActionPerformed

    private void psSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psSIDActionPerformed

    private void pDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDeleteBtnActionPerformed
        if(PatrollingTbl.getSelectionModel().isSelectionEmpty()==false){
            int column = 0;
            int row = PatrollingTbl.getSelectedRow();
            String Id = PatrollingTbl.getModel().getValueAt(PatrollingTbl.convertRowIndexToModel(row), column).toString();
            patrols = Patrols.Delete(patrols, Id);
            Building_Executive_Main bem = new Building_Executive_Main(Session);
            bem.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_pDeleteBtnActionPerformed

    private void pAssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAssignBtnActionPerformed

        if (!psCID.getText().equals("") || 
                !psSID.getText().equals("") || 
                !psTime.getText().equals("") || 
                !psDate.getText().equals("")) 
            {
                p.addFile(psCID.getText(), 
                        psSID.getText(), 
                        psTime.getText(),
                        psDate.getText(),
                        psStatus.getText());
                patrols.add(new Patrols(psCID.getText(), 
                        psSID.getText(), 
                        psTime.getText(),
                        psDate.getText(),
                        psStatus.getText()));
                        
                JOptionPane.showMessageDialog(null, "Successfully Assigned Job!");
                
            } else {
                JOptionPane.showMessageDialog(null, "Missing Inputs");
            }
            DefaultTableModel model = (DefaultTableModel)PatrollingTbl.getModel();
            model.setRowCount(0);
            Patrols.tabulateData(patrols, PatrollingTbl);
        
    }//GEN-LAST:event_pAssignBtnActionPerformed

    private void psTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psTimeActionPerformed

    private void cUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUpdateBtnActionPerformed
        if(ComplaintsTbl.getSelectionModel().isSelectionEmpty()==false){
            int column = 0;
            int row = ComplaintsTbl.getSelectedRow();
            String Id = ComplaintsTbl.getModel().getValueAt(row, column).toString();
            Building_Executive_Update_Complaints beuc = new Building_Executive_Update_Complaints(Session);
            beuc.spamdata(Id);
            beuc.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_cUpdateBtnActionPerformed

    private void psStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psStatusActionPerformed

    private void psDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Building_Executive_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Building_Executive_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Building_Executive_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Building_Executive_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Building_Executive_Main().setVisible(true);
//            }
//       });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ComplaintsTbl;
    private javax.swing.JLabel Date;
    private javax.swing.JTable JobManagementTbl;
    private javax.swing.JLabel Logout1;
    private javax.swing.JTable PatrollingHistoryTbl;
    private javax.swing.JTable PatrollingTbl;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel UID;
    private javax.swing.JLabel Username;
    private javax.swing.JButton cUpdateBtn;
    private javax.swing.JTextField emContact;
    private javax.swing.JTextField emEmail;
    private javax.swing.JTextField emID;
    private javax.swing.JTextField emName;
    private javax.swing.JTextField emPassword;
    private javax.swing.JTextField emRole;
    private javax.swing.JButton jAssignBtn;
    private javax.swing.JButton jClearBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JButton pAssignBtn;
    private javax.swing.JButton pClearBtn;
    private javax.swing.JButton pDeleteBtn;
    private javax.swing.JTextField psCID;
    private javax.swing.JTextField psDate;
    private javax.swing.JTextField psSID;
    private javax.swing.JTextField psStatus;
    private javax.swing.JTextField psTime;
    // End of variables declaration//GEN-END:variables
}
